# Generated by Django 3.2.1 on 2021-05-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=150)),
                ('Username', models.CharField(max_length=150)),
                ('UserApellido', models.CharField(max_length=150)),
                ('MartialStatus', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Pwd', models.CharField(max_length=150)),
                ('Pwd1', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
    ]
