# Generated by Django 3.2.1 on 2021-05-12 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
